use the contaainer to attempt to build the final jar

diff --git a/.github/workflows/manifold.yml b/.github/workflows/manifold.yml
--- a/.github/workflows/manifold.yml
+++ b/.github/workflows/manifold.yml
@@ -13,6 +13,117 @@ on:
     branches: [ master, main ]
 
 jobs:
+  build_linux:
+    timeout-minutes: 45
+    strategy:
+      matrix:
+        cuda_support: [OFF]
+        parallel_backend: [NONE]
+    runs-on: ubuntu-latest
+    if: github.event.pull_request.draft == false || startsWith(github.ref, 'refs/tags/')
+    outputs:
+      java_package_version_changed: ${{ steps.check_version.outputs.changed }}
+    container:
+      image: docker://nvidia/cuda:12.0.1-devel-ubuntu22.04
+    steps:
+    - name: Install dependencies
+      run: |
+        apt-get -y update
+        DEBIAN_FRONTEND=noninteractive apt install -y libomp-dev libassimp-dev git libtbb-dev pkg-config libpython3-dev python3 python3-distutils python3-pip lcov
+        pip install trimesh
+    - uses: actions/checkout@v3
+      with:
+        submodules: recursive
+        fetch-depth: 2
+    - uses: jwlawson/actions-setup-cmake@v1.12
+    - name: Setup Java
+      uses: actions/setup-java@v2
+      with:
+        java-version: '21'
+        distribution: 'adopt'
+    - name: Install Maven
+      run: |
+        apt-get update
+        apt-get install -y maven
+    - name: Cache Maven packages
+      uses: actions/cache@v3
+      with:
+        path: ~/.m2
+        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
+        restore-keys: ${{ runner.os }}-m2
+    - name: Build ${{matrix.backend}}
+      run: |
+        mkdir build
+        cd build
+        cmake -DCMAKE_BUILD_TYPE=Release -DASSIMP_ENABLE=ON -DBUILD_SHARED_LIBS=ON -DMANIFOLD_DEBUG=ON -DMANIFOLD_EXPORT=ON -DMANIFOLD_PAR=${{matrix.parallel_backend}} -DCMAKE_POLICY_VERSION_MINIMUM=3.5 .. && make
+    - name: Get version
+      id: get_version
+      run: echo "VERSION=$(cat bindings/java/version.txt)" >> $GITHUB_ENV
+      shell: bash
+    - name: Check if version has changed
+      id: check_version
+      shell: bash
+      run: |
+        if git diff --quiet HEAD~1 -- bindings/java/version.txt
+        then
+          echo "Version Unchanged!"
+          echo "changed=false" >> "$GITHUB_OUTPUT"
+        else
+          echo "Version Changed!"
+          echo "changed=true" >> "$GITHUB_OUTPUT"
+        fi
+    - name: Build Java package
+      shell: bash
+      run: |
+        cd bindings/java
+
+        BACKEND=""
+        if [ "${{matrix.parallel_backend}}" = "NONE" ] && [ "${{matrix.cuda_support}}" = "ON" ]; then
+            BACKEND="-cuda"
+        elif [ "${{matrix.parallel_backend}}" = "NONE" ] && [ "${{matrix.cuda_support}}" = "OFF" ]; then
+            BACKEND=""
+        elif [ "${{matrix.cuda_support}}" = "ON" ]; then
+            BACKEND="-${{matrix.parallel_backend}}-cuda"
+        else
+            BACKEND="-${{matrix.parallel_backend}}"
+        fi
+
+        mvn versions:set -DnewVersion=$(cat version.txt) --file pom.xml
+        mvn package -Dos.classifier=linux$BACKEND-x86_64
+        find  ./target/classes/ -name "*.class" -delete
+    # - name: Test ${{matrix.parallel_backend}} with CUDA ${{matrix.cuda_support}}
+    #   # note that the test for CUDA backend does not really test CUDA, as we
+    #   # don't have CUDA GPU on GitHub Action
+    #   if: matrix.parallel_backend != 'NONE' || matrix.cuda_support != 'OFF'
+    #   run: |
+    #     export PYTHONPATH=$PYTHONPATH:$(pwd)/build/bindings/python
+    #     cd build/test
+    #     ./manifold_test
+    #- name: Coverage Report
+    #  # only do code coverage for default sequential backend, it seems that TBB
+    #  # backend will cause failure
+    #  # perhaps issue related to invalid memory access?
+    #  if: matrix.parallel_backend == 'NONE' && matrix.cuda_support == 'OFF'
+    #  run: |
+    #    cd build
+    #    cmake -DOUTPUT_TO_BIN=ON -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=ON -DMANIFOLD_PAR=${{matrix.parallel_backend}} -DMANIFOLD_USE_CUDA=${{matrix.cuda_support}} -DCODE_COVERAGE=ON .. && make
+    #    lcov --capture --initial --directory . --output-file ./code_coverage_init.info
+    #    cd bin
+    #    ./manifold_test
+    #    cd ../
+    #    lcov --capture --directory . --output-file ./code_coverage_test.info
+    #    lcov --add-tracefile ./code_coverage_init.info --add-tracefile ./code_coverage_test.info --output-file ./code_coverage_total.info
+    #    lcov --remove ./code_coverage_total.info '/usr/*' '*/third_party/*' '*/test/*' '*/extras/*' '*/bindings/*' --output-file ./code_coverage.info
+    - uses: codecov/codecov-action@v2
+      with:
+        files: build/code_coverage.info
+        fail_ci_if_error: false
+        name: ${{matrix.parallel_backend}}-${{matrix.cuda_support}}
+    - name: Upload artifact
+      uses: actions/upload-artifact@v4  # updated from v3
+      with:
+        name: manifold_java_bindings_linux_${{env.VERSION}}
+        path: bindings/java/target/classes/
 
   build_mac:
     timeout-minutes: 30
@@ -103,7 +214,8 @@ jobs:
   deploy_jars:
     runs-on: ubuntu-latest
     needs: [ build_mac]
-    if: github.event.pull_request.draft == false && ${{needs.build_linux.outputs.java_package_version_changed}} == 'true'
+    container:
+      image: docker://nvidia/cuda:12.0.1-devel-ubuntu22.04
     steps:
     - name: Install dependencies
       run: |
@@ -132,16 +244,6 @@ jobs:
         cd build
         cmake -DCMAKE_BUILD_TYPE=Release -DASSIMP_ENABLE=ON -DBUILD_SHARED_LIBS=ON -DMANIFOLD_DEBUG=ON -DMANIFOLD_EXPORT=ON -DCMAKE_POLICY_VERSION_MINIMUM=3.5 .. && make
  
-    - name: Checkout Code
-      uses: actions/checkout@v3
-      with:
-        submodules: recursive
-        fetch-depth: 2
-    - name: Set up JDK 21
-      uses: actions/setup-java@v3
-      with:
-        java-version: '21'
-        distribution: 'adopt'
     - name: Install Maven
       run: |
         sudo apt-get update
@@ -175,6 +277,7 @@ jobs:
         cd ./bindings/java
         mvn versions:set -DnewVersion=$VERSION --file pom.xml
         mvn package -Dos.classifier=linux-x86_64
+        cd ../../
         find . -name "*.jar"
     - name: Deploy Jar
       shell: bash
